app.py
import os
from flask import Flask, render_template

from settings import APP_FOLDER
from views.contatos_view import contatos_view
from views.pessoas_view import pessoas_view
from db import mysql

app = Flask(__name__)
app.config.from_pyfile(os.path.join(APP_FOLDER, "settings.py"))
mysql.init_app(app)

app.register_blueprint(contatos_view)
app.register_blueprint(pessoas_view)

@app.route('/index', methods=['GET'])
@app.route('/', methods=['GET'])
def index():
  return render_template('main.html', title='CP - Main')

views/contatos_view.py
from flask import render_template, Blueprint, request, jsonify

from db import select
# FIXME: deletar dependencias
from cadastrar import cadastrar_contatos2
from atualizar import atualizar_contatos_telefone2, atualizar_contatos_email2
from deletar import deletar_contatos2

contatos_view = Blueprint('contatos', __name__, url_prefix='/contatos')

@contatos_view.route('/', methods=['GET'])
def cadastrar_contatos0():
  if request.method == 'GET':
    return render_template('contatos.html')
  elif request.method == 'POST':
    id_pessoas = request.form['id_pessoas']
    telefone = request.form['id_telefone']
    email = request.form['id_email']
    return cadastrar_contatos2(id_pessoas, telefone, email)


@contatos_view.route('/list', methods=['GET'])
def consultar_contatos1():
  contatos = select('SELECT * FROM PYTHON_CRUD_PESSOAS.CONTATOS;')
  # TODO: Create html
  return jsonify(contatos)


@contatos_view.route('/atualizar-telefone', methods=['GET', 'POST'])
def atualizar_contatos_telefone0():
  if request.method == 'GET':
    return render_template('contatos_atualizar_telefone.html')
  elif request.method == 'POST':
    telefone = request.form['id_telefone_atualizar']
    cpf = request.form['id_cpf_atualizar']
    return atualizar_contatos_telefone2(telefone, cpf)


@contatos_view.route('/atualizar-email', methods=['GET', 'POST'])
def atualizar_contatos_email0():
  if request.method == 'GET':
    return render_template('contatos_atualizar_email.html')
  elif request.method == 'POST':
    email = request.form['id_email_atualizar']
    cpf = request.form['id_cpf_atualizar']
    return atualizar_contatos_email2 (email, cpf)


@contatos_view.route('/deletar', methods=['GET', 'DELETE'])
def deletar_contatos0():
  if request.method == 'GET':
    return render_template('contatos_deletar.html')
  elif request.method == 'DELETE':
    cpf = request.form['id_cpf_deletar']
    return deletar_contatos2 (cpf)

views/pessoas_view.py
from flask import render_template, Blueprint, request, jsonify

from db import select
# FIXME: deletar dependencias
from cadastrar import cadastrar_pessoas2
from atualizar import atualizar_pessoas2
from deletar import deletar_pessoas2

pessoas_view = Blueprint('pessoas', __name__, url_prefix='/pessoas')

@pessoas_view.route('/', methods=['GET', 'POST'])
def cadastrar_pessoas0():
  if request.method == 'GET':
    return render_template('pessoas.html')
  elif request.method == 'POST':
    nome = request.form['id_nome']
    cpf = request.form['id_cpf']
    return cadastrar_pessoas2(nome, cpf)


@pessoas_view.route('/list', methods=['GET'])
def consultar_pessoas1():
  pessoas = select('SELECT * FROM PYTHON_CRUD_PESSOAS.PESSOAS;')
  # TODO: Create html
  return jsonify(pessoas)


@pessoas_view.route('/contatos-cadastrados', methods=['GET'])
def consultar_pessoas_contatos1():
  SQL_STATEMENT = 'SELECT P.NOME, P.CPF, C.TELEFONE, C.EMAIL '\
      'FROM PYTHON_CRUD_PESSOAS.PESSOAS AS P '\
      'INNER JOIN PYTHON_CRUD_PESSOAS.CONTATOS AS C ON C.ID_PESSOAS = P.ID;'
  nomes = select(SQL_STATEMENT)
  return jsonify(nomes)


@pessoas_view.route('/atualizar', methods=['GET', 'POST'])
def atualizar_pessoas0():
  if request.method == 'GET':
    return render_template('pessoas_atualizar.html')
  elif request.method == 'POST':
    nome = request.form['id_nome_atualizar']
    cpf = request.form['id_cpf_atualizar']
    return atualizar_pessoas2(nome, cpf)


@pessoas_view.route('/deletar', methods=['GET', 'DELETE'])
def deletar_pessoas0():
  if request.method == 'GET':
    return render_template('pessoas_deletar.html')
  elif request.method == 'DELETE':
    cpf = request.form['id_cpf_deletar']
    return deletar_pessoas2 (cpf)

templates/contatos.html
{% extends 'layout.html' %}

{% block content %}
    <h3>Cadastro do Contato</h3>
    <form action = "{{ url_for('contatos.cadastrar_contatos0') }}" method = "POST">
        <label for="">Id da Pessoa: </label>
        <input type="text" name="id_pessoas" id="id_pessoas"><br><br>
        <label for="">Telefone: </label>
        <input type="text" name="id_telefone" id="id_telefone"><br><br>
        <label for="">E-mail: </label>
        <input type="text" name="id_email" id="id_email"><br><br>
        <input type="submit" name="retorno" value="Enviar">
    </form><br>

{% endblock %}

templates/contatos_atualizar_email.html
{% extends 'layout.html' %}

{% block content %}
    <h3>Atualizar E-mail de Pessoa Cadastrada</h3>
    <form action = "{{ url_for('contatos.atualizar_contatos_email0') }}" method = "POST">
        <label for="">CPF: </label>
        <input type="text" name="id_cpf_atualizar" id="id_cpf_atualizar"><br><br>
        <label for="">E-mail: </label>
        <input type="text" name="id_email_atualizar" id="id_email_atualizar"><br><br>
        <input type="submit" name="retorno" value="Atualizar">
    </form><br>

{% endblock %}

templates/contatos_atualizar_telefone.html
{% extends 'layout.html' %}

{% block content %}
    <h3>Atualizar Telefone de Pessoa Cadastrada</h3>
    <form action = "{{ url_for('contatos.atualizar_contatos_telefone0') }}" method = "POST">
        <label for="">CPF: </label>
        <input type="text" name="id_cpf_atualizar" id="id_cpf_atualizar"><br><br>
        <label for="">Telefone: </label>
        <input type="text" name="id_telefone_atualizar" id="id_telefone_atualizar"><br><br>
        <input type="submit" name="retorno" value="Atualizar">
    </form><br>

{% endblock %}

templates/contatos_deletar.html
{% extends 'layout.html' %}

{% block content %}
    <h3>Deletar Contato de Pessoa Cadastrada</h3>
    <form action = "{{ url_for('contatos.deletar_contatos0') }}" method = "POST">
        <label for="">CPF: </label>
        <input type="text" name="id_cpf_deletar" id="id_cpf_deletar"><br><br>
        <input type="submit" name="retorno" value="Deletar">
    </form><br>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{title or 'CP'}}</title>

  <!-- Bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar  navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Pessoa CRUD</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>      
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Sobre</a>
          </li>
        </ul>
        <span class="navbar-text">
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>      
        </span>
      </div>
    </div>
  </nav>  

  {% block content %} {% endblock %}

  <nav class="navbar fixed-bottom navbar-light bg-light">
    <div class="container">
      <span class="navbar-text">
        2022 |  <a href="https://github.com/altherlex/python_crud_pessoa" target="_blank">Source Code</a>
      </span>
    </div>
  </nav>  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>  
</body>
</html>

templates/main.html
{% extends 'layout.html' %}

{% block content %}

  <div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Pessoas
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne">
        <div class="accordion-body">
          <ol class="list-group list-group-flush list-group-numbered">
            <li class="list-group-item">
              <a href="/pessoas">Pessoas: cadastrar</a>
            </li>
            <li class="list-group-item">
              <a href="/pessoas/atualizar">Pessoas: atualizar</a>
            </li>
            <li class="list-group-item">
              <a href="/pessoas/deletar">Pessoas: deletar</a>
            </li>
            <li class="list-group-item">
              <a href="/pessoas/list">Pessoas: consultar</a>
            </li>
          </ol>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Contatos
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo">
        <div class="accordion-body">
          <ol class="list-group list-group-flush list-group-numbered">
            <li class="list-group-item">
              <a href="/contatos">Contatos: cadastrar</a>
            </li>
            <li class="list-group-item">
              <a href="/contatos/atualizar-email">Atualizar E-mail</a>
            </li>
            <li class="list-group-item">
              <a href="/contatos/atualizar-telefone">Atualizar Telefone</a>
            </li>
            <li class="list-group-item">
              <a href="/contatos/deletar">Contatos: deletar</a>
            </li>
            <li class="list-group-item">
              <a href="/contatos/list">Contatos: consultar</a>
            </li>
          </ol>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingThree">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Consulta Consolidada
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree">
        <div class="accordion-body">
          <ol class="list-group list-group-flush list-group-numbered">
            <li class="list-group-item">
              <a href="/pessoas-contatos-cadastrados">Consultar Pessoas e Contatos</a>
            </li>
          <ol>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/pessoas.html
{% extends 'layout.html' %}

{% block content %}
    <h3>Cadastro da Pessoa</h3>
    <form action = "{{ url_for('pessoas.cadastrar_pessoas0') }}" method = "POST">
        <label for="">Nome: </label>
        <input type="text" name="id_nome" id="id_nome"><br><br>
        <label for="">CPF: </label>
        <input type="text" name="id_cpf" id="id_cpf"><br><br>
        <input type="submit" name="retorno" value="Enviar">
    </form>

{% endblock %}

templates/pessoas_atualizar.html
{% extends 'layout.html' %}

{% block content %}
    <h3>Atualizar Nome de Pessoa Cadastrada</h3>
    <form action = "{{ url_for('pessoas.atualizar_pessoas0') }}" method = "POST">
        <label for="">CPF: </label>
        <input type="text" name="id_cpf_atualizar" id="id_cpf_atualizar"><br><br>
        <label for="">Nome: </label>
        <input type="text" name="id_nome_atualizar" id="id_nome_atualizar"><br><br>
        <input type="submit" name="retorno" value="Atualizar">
    </form><br>

{% endblock %}

templates/pessoas_deletar.html
{% extends 'layout.html' %}

{% block content %}
    <h3>Atualizar Nome de Pessoa Cadastrada</h3>
    <form action = "{{ url_for('pessoas.deletar_pessoas0') }}" method = "POST">
        <label for="">CPF: </label>
        <input type="text" name="id_cpf_deletar" id="id_cpf_deletar"><br><br>
        <input type="submit" name="retorno" value="Deletar">
    </form><br>

{% endblock %}